route:
  receiver: 'mail'
  repeat_interval: 4h
  group_by: [ alertname ]


receivers:
  - name: 'mail'
    email_configs:
      - smarthost: 'smtp.gmail.com:465'
        auth_username: 'Dveyn_d@mail.ru'
        auth_password: "63317DveyN63317"
        from: 'dveyn_d@mail.com'
        to: 'dveyny@gmail.com'
