global:
  scrape_interval: 30s
  scrape_timeout: 10s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'prometheus:9090'
  
  - job_name: Jenkins
    static_configs:
      - targets: [ 'http://3.252.193.23:8080' ]
      
  - job_name: App
    static_configs:
      - targets: [ 'http://3.252.193.23:80' ]


alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: [ 'alertmanager:9093' ]
